Fix using `dep`
Fix as `uuid.Must` caused an error

```
./vsq_sqs.go:31:53: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)
FAIL	github.com/abetomo/vsq.go [build failed]
```